name: Deploy

on:
  push:
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Switch node version
        uses: actions/setup-node@v1
        with:
          node-version: "10.16.3"
      - name: Install dependencies
        run: npm i
      - name: Check lint error
        run: npm run lint
  build-and-deploy:
    runs-on: ubuntu-18.04
    needs: lint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Switch node version
        uses: actions/setup-node@v1
        with:
          node-version: "10.16.3"
      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./bin/bump-version.sh
      - name: Install dependencies
        run: npm i
      - name: Set env
        run: bin/set-env.sh
      - name: Build
        run: npm run build
      - name: Deploy to firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: ./bin/deploy.sh
      - name: Push version change to GitHub
        run: |
          if [ ! "$GITHUB_EVENT_NAME" = "release" ] ; then
            exit 0
          fi
          git push origin master
